### PR TITLE
Add proper conversion for setting temperature values, make driver and…

### PR DESCRIPTION
**Pull request by digitaldan**
… passenger temperature channels writable

Signed-off-by: digitaldan <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
@kaikreuzer while testing temperature controls i realized that while we have a `temperature`  channel, there is no "temperature" value in the API, only `driver_temp` and `passeneger_temp`.  We do have these channels, but they are write only. This makes using temperature controls in the UI clients very difficult.   
 
The API does support setting the driver and passenger values in a single call, and that is what the `temperature`  channel does,  but since it does not have its own value, again makes it tough to use (you always need driver and/or passenger + temperature )

I First enabled allowing the  driver and passenger channels to set individual values.  but ran into a bug in the Tesla API where sometimes only the Driver setting would change the temp, and other times only the passenger setting would change the temp.  In the end the only reliable way to change the temperature is to set both the  driver and passenger value to the same thing.  

This is a long way of saying, i think we should enable the driver and passenger channels to set the combined temp, i was surprised that it did not work this way.

As an alternative, we could populate the `temperature`  channel with the average of the two values so that it is more useful , that would also seem more expected then how it work now

**Comment by digitaldan** [comment]
Actually , now that i think about it, I like renaming "temperature" to `combined_temp` which matches the `driver_temp` and `passenger_temp` syntax,  and make that the average of the two, and changing it sets  both to the same value.

I can then also enable driver and passenger values to be set individually  as the API allows,  which works 
 sometimes (and hopefully Tesla fixes it) , and in the meantime we can add this to the readme.

**Comment by digitaldan** [comment]
So I was a bit mistaken, setting driver and passenger temps do absolutely work, its just that i had my car set to "sync" mode, which i thought i had turned off.  I tested another popular 3rd party Tesla app, and it has the same behavior (Tesla Remote for IOS) . The API does not tell you if this is on or not. 

So this PR adds the ability to change driver and  passenger temps, as well as a "combined" temp which mimics the GUI in the car.  This replaces the "temperature" channel which does not really make sense as there are many "temperatures" associated with the car.

**Review by kaikreuzer — APPROVED** [review]
Thanks, sounds like the right thing to do!

**Pull request merged**
